import fs from 'fs';
import path from 'path';

export interface MinivercelConfig {
  buildCommand?: string;
  installCommand?: string;
  outputDirectory?: string;
}

export type Framework = 'nextjs' | 'vite' | 'cra' | 'node';

export interface DetectedFramework {
  framework: Framework;
  config: MinivercelConfig;
}

export function detectFramework(projectPath: string): DetectedFramework {
  let config: MinivercelConfig = {};
  
  const configPath = path.join(projectPath, 'minivercel.json');
  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = JSON.parse(content);
    } catch (err) {
      console.warn('Warning: Failed to parse minivercel.json, using defaults.', err);
    }
  }

  const packageJsonPath = path.join(projectPath, 'package.json');
  if (!fs.existsSync(packageJsonPath)) {
    return { framework: 'node', config };
  }

  let pkg: any = {};
  try {
    pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
  } catch (err) {
    console.warn('Warning: Failed to parse package.json.', err);
    return { framework: 'node', config };
  }

  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };

  if (deps['next']) {
    return { framework: 'nextjs', config };
  }

  if (deps['vite']) {
    return { framework: 'vite', config };
  }

  if (deps['react-scripts']) {
    return { framework: 'cra', config };
  }

  return { framework: 'node', config };
}

export function ensureDockerAssets(projectPath: string): void {
  const { framework, config } = detectFramework(projectPath);

  const dockerfilePath = path.join(projectPath, 'Dockerfile');
  const dockerignorePath = path.join(projectPath, '.dockerignore');

  // 1. Generate .dockerignore if missing
  if (!fs.existsSync(dockerignorePath)) {
    const ignoreContent = `
node_modules
.git
data.sqlite
.next
dist
build
Dockerfile
.dockerignore
`.trim();
    fs.writeFileSync(dockerignorePath, ignoreContent + '\n');
    console.log('Created optimized .dockerignore file.');
  }

  // 2. Generate Dockerfile if missing
  if (!fs.existsSync(dockerfilePath)) {
    console.log(`Auto-detected framework: ${framework}`);
    let dockerfileContent = '';

    const installCmd = config.installCommand || 'npm install';

    const packageJsonPath = path.join(projectPath, 'package.json');
    let hasBuildScript = false;
    let hasStartScript = false;
    let mainFile = 'index.js';
    if (fs.existsSync(packageJsonPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
        hasBuildScript = !!(pkg.scripts && pkg.scripts.build);
        hasStartScript = !!(pkg.scripts && pkg.scripts.start);
        if (pkg.main) mainFile = pkg.main;
      } catch (_) {}
    }

    if (framework === 'nextjs') {
      const buildCmd = config.buildCommand || 'npm run build';
      dockerfileContent = `
# Auto-generated by Mini-Vercel for Next.js
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN ${installCmd}
COPY . .
RUN ${buildCmd}
EXPOSE 3000
ENV PORT=3000
CMD ["npm", "start"]
`.trim();
    } else if (framework === 'vite') {
      const buildCmd = config.buildCommand || 'npm run build';
      const outDir = config.outputDirectory || 'dist';
      dockerfileContent = `
# Auto-generated by Mini-Vercel for Vite (Static SPA)
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN ${installCmd}
COPY . .
RUN ${buildCmd}

FROM nginx:alpine
COPY --from=builder /app/${outDir} /usr/share/nginx/html
EXPOSE 80
`.trim();
    } else if (framework === 'cra') {
      const buildCmd = config.buildCommand || 'npm run build';
      const outDir = config.outputDirectory || 'build';
      dockerfileContent = `
# Auto-generated by Mini-Vercel for Create React App (Static SPA)
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN ${installCmd}
COPY . .
RUN ${buildCmd}

FROM nginx:alpine
COPY --from=builder /app/${outDir} /usr/share/nginx/html
EXPOSE 80
`.trim();
    } else {
      const buildCmd = config.buildCommand ? `RUN ${config.buildCommand}` : (hasBuildScript ? 'RUN npm run build' : '');
      const startCmd = hasStartScript ? 'CMD ["npm", "start"]' : `CMD ["node", "${mainFile}"]`;
      
      dockerfileContent = `
# Auto-generated by Mini-Vercel for Node.js
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN ${installCmd}
COPY . .
${buildCmd}
EXPOSE 3000
ENV PORT=3000
${startCmd}
`.trim();
    }

    // Filter out any empty lines resulting from optional buildCmd
    const cleanedContent = dockerfileContent
      .split('\n')
      .filter(line => line.trim() !== '')
      .join('\n');

    fs.writeFileSync(dockerfilePath, cleanedContent + '\n');
    console.log(`Created optimized Dockerfile for ${framework}.`);
  }
}
